#### FalconAC Config
#
# Hey there,
#   Thanks for using FalconAC v2! This version is a rewrite for stronger check and lower resource cost.
#   Feel free to read through the descriptions of checks and options and change them to suit your server.
#   I hope that FalconAC will perform well and live up to your expectations.
#      - Liulihaocai

checks:
  killaura:
    hit:
      range: 3.5