#### FalconAC Config
#
# Hey there,
#   Thanks for using FalconAC v2! This version is a rewrite for stronger check and lower resource cost.
#   Feel free to read through the descriptions of checks and options and change them to suit your server.
#   I hope that FalconAC will perform well and live up to your expectations.
#      - Liulihaocai
#
# 开始使用:
#  VL的意思是Violence Level，这个值决定了反作弊检测玩家的策略(例如kick，严格模式等)

brand: "&6M&belhor"

badpackets:
  # 如果玩家发送了有严重问题的数据包，这个玩家将会直接被踢
  # 当这个值是false时，损坏的数据包将被忽略
  instant-kick: true
  # 损坏的战斗包 - 未知实体id
  # 这个选项可能和其他反作弊中的假人冲突
  attack-id: true
  # 尝试攻击自己(自伤disabler?)
  attack-self: true
  # 损坏的快捷栏切换包
  slot: true
  # 在空中发送跳跃Action包(AirJump)
  air-jump: true
  # 不正常的pitch(derp?)
  illegal-pitch: true

checks:
  fight:
    hit:
      baseVL: 20
      onlyStrict: false
      range: 3.5
      angleDiff: 60